services:
  app:
    build: .
    container_name: mopay_dev
    restart: unless-stopped
    environment:
#      - PORT=8010
      - DB_FILE=/data/mopay.sqlite
      - APP_PIN=123456
      - NODE_ENV=production
    volumes:
      - ./data:/data
    ports:
      - "9010:8010"
